// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BackBaseTask.BackBaseTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Add new computer", SourceFile="BackBaseTests\\AddNewComputerFlow.feature", SourceLine=0)]
    public partial class AddNewComputerFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AddNewComputerFlow.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Add new computer", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add new computer without name", new string[] {
                "AddANewComputer"}, SourceLine=4)]
        public virtual void AddNewComputerWithoutName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add new computer without name", new string[] {
                        "AddANewComputer"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given("I set the computer name to \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
 testRunner.And("I set the Introduced date to \"2015-11-18\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.And("I set the Discontinued date to \"2016-11-18\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And("I set the Company to \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.When("I press Create this computer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.Then("response code should be \"BadRequest\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void AddANewComputerPositiveFlow(string exampleDescription, string name, string introduced, string discontinued, string company, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "PositiveCases"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add a new computer positive flow", @__tags);
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given(string.Format("I set the computer name to \"{0}\"", name), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 19
 testRunner.And(string.Format("I set the Introduced date to \"{0}\"", introduced), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
 testRunner.And(string.Format("I set the Discontinued date to \"{0}\"", discontinued), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.And(string.Format("I set the Company to \"{0}\"", company), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.When("I press Create this computer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 23
 testRunner.Then("response message should contain \"Done!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 24
 testRunner.And("response code should be \"OK\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer positive flow, 0_Empty_Introduced_Date", new string[] {
                "PositiveCases"}, SourceLine=26)]
        public virtual void AddANewComputerPositiveFlow_0_Empty_Introduced_Date()
        {
            this.AddANewComputerPositiveFlow("0_Empty_Introduced_Date", "Specflow_EmptyIntroduced", "", "2016-11-18", "1", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer positive flow, 1_Empty_Discontinued_Date", new string[] {
                "PositiveCases"}, SourceLine=27)]
        public virtual void AddANewComputerPositiveFlow_1_Empty_Discontinued_Date()
        {
            this.AddANewComputerPositiveFlow("1_Empty_Discontinued_Date", "Specflow_EmptyDiscontinued", "2015-11-18", "", "2", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer positive flow, 2_Empty_Company", new string[] {
                "PositiveCases"}, SourceLine=28)]
        public virtual void AddANewComputerPositiveFlow_2_Empty_Company()
        {
            this.AddANewComputerPositiveFlow("2_Empty_Company", "Specflow_EmptyCompany", "2015-11-18", "2016-11-18", "", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer positive flow, 3_Empty_Dates", new string[] {
                "PositiveCases"}, SourceLine=29)]
        public virtual void AddANewComputerPositiveFlow_3_Empty_Dates()
        {
            this.AddANewComputerPositiveFlow("3_Empty_Dates", "Specflow_EmptyDates", "", "", "3", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer positive flow, 4_Empty_DiscontinuedDate_And_Company", new string[] {
                "PositiveCases"}, SourceLine=30)]
        public virtual void AddANewComputerPositiveFlow_4_Empty_DiscontinuedDate_And_Company()
        {
            this.AddANewComputerPositiveFlow("4_Empty_DiscontinuedDate_And_Company", "Specflow_EmptyDiscontCompany", "2015-11-18", "", "", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer positive flow, 5_Empty_IntroducedDate_And_Company", new string[] {
                "PositiveCases"}, SourceLine=31)]
        public virtual void AddANewComputerPositiveFlow_5_Empty_IntroducedDate_And_Company()
        {
            this.AddANewComputerPositiveFlow("5_Empty_IntroducedDate_And_Company", "Specflow_EmptyIntrodCompany", "", "2016-11-18", "", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer positive flow, 6_Only_Name", new string[] {
                "PositiveCases"}, SourceLine=32)]
        public virtual void AddANewComputerPositiveFlow_6_Only_Name()
        {
            this.AddANewComputerPositiveFlow("6_Only_Name", "Specflow_Only_Name", "", "", "", ((string[])(null)));
        }
        
        public virtual void AddANewComputerDatesTesting(string exampleDescription, string name, string introduced, string discontinued, string expected_Response, string expected_Code, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DatesTesting"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add a new computer, dates testing", @__tags);
#line 39
this.ScenarioSetup(scenarioInfo);
#line 40
 testRunner.Given(string.Format("I set the computer name to \"{0}\"", name), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 41
 testRunner.And(string.Format("I set the Introduced date to \"{0}\"", introduced), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 42
 testRunner.And(string.Format("I set the Discontinued date to \"{0}\"", discontinued), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 43
 testRunner.And("I set the Company to \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 44
 testRunner.When("I press Create this computer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 45
 testRunner.Then(string.Format("response message should contain \"{0}\"", expected_Response), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 46
 testRunner.And(string.Format("response code should be \"{0}\"", expected_Code), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer, dates testing, 0_Normal_Dates", new string[] {
                "DatesTesting"}, SourceLine=48)]
        public virtual void AddANewComputerDatesTesting_0_Normal_Dates()
        {
            this.AddANewComputerDatesTesting("0_Normal_Dates", "Specflow_Normal_Dates", "2015-11-18", "2016-11-18", "Done!", "OK", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer, dates testing, 1_Zero_Year", new string[] {
                "DatesTesting"}, SourceLine=49)]
        public virtual void AddANewComputerDatesTesting_1_Zero_Year()
        {
            this.AddANewComputerDatesTesting("1_Zero_Year", "Specflow_Zero_Year", "0-1-1", "9999-12-12", "Done!", "OK", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer, dates testing, 2_Intro_DateFormat_dd-MM-yyyy", new string[] {
                "DatesTesting"}, SourceLine=50)]
        public virtual void AddANewComputerDatesTesting_2_Intro_DateFormat_Dd_MM_Yyyy()
        {
            this.AddANewComputerDatesTesting("2_Intro_DateFormat_dd-MM-yyyy", "Specflow_DateFormat_dd-MM-yyyy", "31-12-2000", "", "", "400", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer, dates testing, 3_Disc_DateFormat_dd-MM-yyyy", new string[] {
                "DatesTesting"}, SourceLine=51)]
        public virtual void AddANewComputerDatesTesting_3_Disc_DateFormat_Dd_MM_Yyyy()
        {
            this.AddANewComputerDatesTesting("3_Disc_DateFormat_dd-MM-yyyy", "Specflow_DateFormat_dd-MM-yyyy", "", "31-12-2000", "", "400", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer, dates testing, 4_Intro_Text_Month", new string[] {
                "DatesTesting"}, SourceLine=52)]
        public virtual void AddANewComputerDatesTesting_4_Intro_Text_Month()
        {
            this.AddANewComputerDatesTesting("4_Intro_Text_Month", "Specflow_Text_Month", "2015-Nov-18", "", "", "400", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer, dates testing, 5_Disc_Intro_Text_Month", new string[] {
                "DatesTesting"}, SourceLine=53)]
        public virtual void AddANewComputerDatesTesting_5_Disc_Intro_Text_Month()
        {
            this.AddANewComputerDatesTesting("5_Disc_Intro_Text_Month", "Specflow_Intro_Text_Month", "", "2015-Nov-18", "", "400", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer, dates testing, 6_Intro_Negative_Year", new string[] {
                "DatesTesting"}, SourceLine=54)]
        public virtual void AddANewComputerDatesTesting_6_Intro_Negative_Year()
        {
            this.AddANewComputerDatesTesting("6_Intro_Negative_Year", "Specflow_Negative_Year", "-1-11-11", "", "", "400", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer, dates testing, 7_Disc_Negative_Year", new string[] {
                "DatesTesting"}, SourceLine=55)]
        public virtual void AddANewComputerDatesTesting_7_Disc_Negative_Year()
        {
            this.AddANewComputerDatesTesting("7_Disc_Negative_Year", "Specflow_Negative_Year", "", "-1-11-11", "", "400", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer, dates testing, 8_Intro_Wrong_Delimiter", new string[] {
                "DatesTesting"}, SourceLine=56)]
        public virtual void AddANewComputerDatesTesting_8_Intro_Wrong_Delimiter()
        {
            this.AddANewComputerDatesTesting("8_Intro_Wrong_Delimiter", "Specflow_Wrong_Delimiter", "2000/1/1", "", "", "400", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer, dates testing, 9_Disc_Wrong_Delimiter", new string[] {
                "DatesTesting"}, SourceLine=57)]
        public virtual void AddANewComputerDatesTesting_9_Disc_Wrong_Delimiter()
        {
            this.AddANewComputerDatesTesting("9_Disc_Wrong_Delimiter", "Specflow_Wrong_Delimiter", "", "2000/1/1", "", "400", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer, dates testing, 10_Intro_Text_Date", new string[] {
                "DatesTesting"}, SourceLine=58)]
        public virtual void AddANewComputerDatesTesting_10_Intro_Text_Date()
        {
            this.AddANewComputerDatesTesting("10_Intro_Text_Date", "Specflow_Text_Date", "text", "", "", "400", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer, dates testing, 11_Intro_Text_Date", new string[] {
                "DatesTesting"}, SourceLine=59)]
        public virtual void AddANewComputerDatesTesting_11_Intro_Text_Date()
        {
            this.AddANewComputerDatesTesting("11_Intro_Text_Date", "Specflow_Text_Date", "", "text", "", "400", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer, dates testing, 12_Intro_DateFormat_dd-MM-yyyy", new string[] {
                "DatesTesting"}, SourceLine=60)]
        public virtual void AddANewComputerDatesTesting_12_Intro_DateFormat_Dd_MM_Yyyy()
        {
            this.AddANewComputerDatesTesting("12_Intro_DateFormat_dd-MM-yyyy", "Specflow_DateFormat_MM-dd-yyyy", "12-31-2000", "", "", "400", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer, dates testing, 13_Disc_DateFormat_dd-MM-yyyy", new string[] {
                "DatesTesting"}, SourceLine=61)]
        public virtual void AddANewComputerDatesTesting_13_Disc_DateFormat_Dd_MM_Yyyy()
        {
            this.AddANewComputerDatesTesting("13_Disc_DateFormat_dd-MM-yyyy", "Specflow_DateFormat_MM-dd-yyyy", "", "12-31-2000", "", "400", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer, dates testing, 14_Intro_Space_Delimiter", new string[] {
                "DatesTesting"}, SourceLine=62)]
        public virtual void AddANewComputerDatesTesting_14_Intro_Space_Delimiter()
        {
            this.AddANewComputerDatesTesting("14_Intro_Space_Delimiter", "Specflow_Space_Delimiter", "2000 1 1", "", "", "400", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer, dates testing, 15_Disc_Space_Delimiter", new string[] {
                "DatesTesting"}, SourceLine=63)]
        public virtual void AddANewComputerDatesTesting_15_Disc_Space_Delimiter()
        {
            this.AddANewComputerDatesTesting("15_Disc_Space_Delimiter", "Specflow_Space_Delimiter", "", "2000 1 1", "", "400", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer, dates testing, 16_Intro_30_Feb", new string[] {
                "DatesTesting"}, SourceLine=64)]
        public virtual void AddANewComputerDatesTesting_16_Intro_30_Feb()
        {
            this.AddANewComputerDatesTesting("16_Intro_30_Feb", "Specflow_30_Feb", "2012-2-30", "", "", "400", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add a new computer, dates testing, 16_Disc_30_Feb", new string[] {
                "DatesTesting"}, SourceLine=65)]
        public virtual void AddANewComputerDatesTesting_16_Disc_30_Feb()
        {
            this.AddANewComputerDatesTesting("16_Disc_30_Feb", "Specflow_30_Feb", "", "2012-2-30", "", "400", ((string[])(null)));
        }
        
        public virtual void AddNewComputerCompanyFieldTesting(string exampleDescription, string company, string expected_Response, string expected_Code, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CompanyTesting"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add new computer, company field testing", @__tags);
#line 71
this.ScenarioSetup(scenarioInfo);
#line 72
 testRunner.Given("I set the computer name to \"Specflow_CompanyTesting\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 73
 testRunner.And("I set the Introduced date to \"2015-11-18\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 74
 testRunner.And("I set the Discontinued date to \"2016-11-18\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 75
 testRunner.And(string.Format("I set the Company to \"{0}\"", company), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 76
 testRunner.When("I press Create this computer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 77
 testRunner.Then(string.Format("response message should contain \"{0}\"", expected_Response), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 78
 testRunner.And(string.Format("response code should be \"{0}\"", expected_Code), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add new computer, company field testing, 0_Company_0", new string[] {
                "CompanyTesting"}, SourceLine=80)]
        public virtual void AddNewComputerCompanyFieldTesting_0_Company_0()
        {
            this.AddNewComputerCompanyFieldTesting("0_Company_0", "0", "Done!", "OK", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add new computer, company field testing, 1_Negative_Company", new string[] {
                "CompanyTesting"}, SourceLine=81)]
        public virtual void AddNewComputerCompanyFieldTesting_1_Negative_Company()
        {
            this.AddNewComputerCompanyFieldTesting("1_Negative_Company", "-1", "Done!", "OK", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add new computer, company field testing, 2_Company_Code_Not_in_List", new string[] {
                "CompanyTesting"}, SourceLine=82)]
        public virtual void AddNewComputerCompanyFieldTesting_2_Company_Code_Not_In_List()
        {
            this.AddNewComputerCompanyFieldTesting("2_Company_Code_Not_in_List", "9999999", "Done!", "OK", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add new computer, company field testing, 3_Company_Code_is_Text", new string[] {
                "CompanyTesting"}, SourceLine=83)]
        public virtual void AddNewComputerCompanyFieldTesting_3_Company_Code_Is_Text()
        {
            this.AddNewComputerCompanyFieldTesting("3_Company_Code_is_Text", "text", "", "400", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
